### ISSUE TITLE
Segment/SEGAnalytics.h file not found Obj-C + cocoapods

### ISSUE THREAD

**Issue by sabrina-li** [segmentio/analytics-ios#1007]
Following the guide here:
https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/

After adding the pod and trying to `#import <Segment/SEGAnalytics.h>`, I'm seeing the below error 

`Segment/SEGAnalytics.h file not found`
<img width="823" alt="Screen Shot 2021-07-20 at 5 39 55 PM" src="https://user-images.githubusercontent.com/46504647/126398993-e5c17542-28ee-4ec2-9939-6d5ae763fd9b.png">

This, however, seem to work, but it feels inconsistent with pod conventions
`#import <Segment.h>`

Here is a demo project I've built: https://github.com/sabrina-li/segment-test-demo-app

Any help would be appreciated!

**Comment by alanjcharles** [comment]
Hi @sabrina-li! I would make sure you are using the latest version of `analytics-ios`. Otherwise it's rather difficult to say without more information.  Would you be able to reach out to friends@segment.com for additional troubleshooting support? They will be able to respond in a more regular cadence and escalate issues to engineering accordingly, if necessary. Thanks, good lyck!
