### ISSUE TITLE
Same issue remain mp_base64EncodedString when active mixpanel

### ISSUE THREAD

**Issue by hamdan** [segmentio/analytics-ios#34]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteMutableData mp_base64EncodedString]: unrecognized selector sent to instance 0xae93160'
**\* First throw call stack:
(0x344d012 0x30f2e7e 0x34d84bd 0x343cbbc 0x343c94e 0x1e05e6 0x1e3768 0x1e31d6 0x2b3b2c0 0x340c376 0x340be06 0x33f3a82 0x33f2f44 0x33f2e1b 0x337c7e3 0x337c668 0x2036ffc 0x3172 0x30a5)
libc++abi.dylib: terminate called throwing an exception

**Comment by lemonkey** [comment]
Somewhat related, I'm seeing the following when attempting to inspect NSData objects from the debug console, but can't see any evidence that these methods are being called directly and your "mp_" prefix for the category method names should be safe:

(lldb) po someData
> 
> error: class method 'mp_dataFromBase64String:' has incompatible result types in different translation units ('id *' vs. 'NSData *')
> error: instance method 'mp_base64EncodedString' has incompatible result types in different translation units ('void *' vs. 'NSString *')
> note: class method 'mp_dataFromBase64String:' also declared here
> note: instance method 'mp_base64EncodedString' also declared here
> error: 2 errors parsing expression
> 

Same thing happens if I try to explicitly call the Apple methods:

> (lldb) po [someData base64EncodedString]
> error: class method 'mp_dataFromBase64String:' has incompatible result types in different translation units ('id *' vs. 'NSData *')
> error: instance method 'mp_base64EncodedString' has incompatible result types in different translation units ('void *' vs. 'NSString *')
> note: class method 'mp_dataFromBase64String:' also declared here
> note: instance method 'mp_base64EncodedString' also declared here
> error: 2 errors parsing expression
> 

I have to resort to printing the object's description from the runtime variable list...
