### ISSUE TITLE
Ability to change write key on the fly?

### ISSUE THREAD

**Issue by DimaVartanian** [segmentio/analytics-ios#476]
Looks like the Swift library has the ability to do this actually. Would it be possible to return a SEGAnalytics instance and allow the app to save and use that rather than a singleton? Our beta/enterprise releases give users the ability to switch between our production and sandbox environments and it would be nice to change the write key based on that to allow events to go to the right place (as we are also using these events to identify users elsewhere).

**Comment by f2prateek** [comment]
Not currently. I would like to do this eventually, especially since we also do it in the Android library. It's not terribly hard, but the problem comes from bundled integrations, and since very few of them have the ability to have multiple instances, having multiple instances of the the segment analytics client but a single instance of say the Mixpanel SDK is likely to cause problems. The Swift library doesn't have any bundled integrations, so it can get away with it.

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-135

**Comment by pavermakov** [comment]
Any updates on it?

**Comment by alanjcharles** [comment]
Hi @pavermakov this isn't something we will likely pursue for this library, I'm afraid. I would definitely recommend checking out our new analytics-swift pilot for a more programmatic approach to your analytics implementation: 

https://github.com/segmentio/analytics-swift
