### ISSUE TITLE
Analytics (~> 3.0) min target issues

### ISSUE THREAD

**Issue by matrosovDev** [segmentio/analytics-ios#512]
- `Analytics (~> 3.0)` required by `Podfile`

Specs satisfying the `Analytics (~> 3.0)` dependency were found, but they required a higher minimum deployment target.

What target should I use?

**Comment by f2prateek** [comment]
iOS 8

**Comment by andrewloyola** [comment]
One comment on this, since it's not as simple as just using iOS8.  

I had iOS9 as my minimum target and was getting this same error with the latest non-beta cocoapods version as of this writing (0.39.0).  There was a bug https://github.com/CocoaPods/CocoaPods/issues/4373 in dependency checking that has since been fixed, and upgrading to beta 1.0.0 b5 worked for me.
