### ISSUE TITLE
Invalid Binary due to Bluetooth usage

### ISSUE THREAD

**Issue by trilorez** [segmentio/analytics-ios#596]
Hi, I tried to submit an app to the AppStore that uses this as a dependency. The binary I submitted was rejected because:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

I believe this is due to this library's use of `CoreBluetooth`.

**Comment by f2prateek** [comment]
Yup we'll make this optional like IDFA collection.

For now you could set NSBluetoothPeripheralUsageDescription as described in the message to explain that it's being used for analytics.

**Comment by f2prateek** [comment]
Available in https://github.com/segmentio/analytics-ios/blob/master/CHANGELOG.md#version-350-12th-september-2016

**Comment by mlazari** [comment]
For me the binary is still rejected with version 3.5.0 of this pod:
pod "Analytics", "3.5.0"
If I remove this pod, the binary is accepted.
I tried to set shouldUseBluetooth to NO explicitly but it is still not accepted. Any idea why is this happening?
The issue is the same as trilorez's:
This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by f2prateek** [comment]
@mlazari did you use any bundled integrations in your submission that was rejected?

**Comment by mlazari** [comment]
I've used
pod "Segment-GoogleAnalytics", "1.1.4"
pod "Segment-Facebook-App-Events", "1.0.3"

I tried to remove these 2 pods, but the issue didn't disappear. It only disappears when I remove this pod:
pod "Analytics", "3.5.0"

**Comment by ladanazita** [comment]
Hey @mlazari and @trilorez , see #606 for a temporary work around while we look into this

**Comment by mlazari** [comment]
@ladanazita Thank you
