### ISSUE TITLE
App rejection - Bluetooth usage description 

### ISSUE THREAD

**Issue by obolton** [segmentio/analytics-ios#606]
Hello,

We are using version 3.5.0 of the library, and are not enabling the `shouldUseBluetooth` flag, but our app is being rejected from the iOS App Store with the following error:

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.
`

The changelog for version 3.5.0 suggests that we should only need to set that key if `shouldUseBluetooth` is `true`, but it doesn't seem to be the case for us.

(As an aside, we don't use CoreBluetooth elsewhere.)

Any help is much appreciated,

Oliver

**Comment by lukeivers** [comment]
Ditto this exact thing.

It appears if you even link in the BT stuff at all, it requires the UsageDescription string.

Perhaps you could refactor this to a subspec so that the CoreBluetooth stuff isn't linked unless someone's making an active decision to use it?

Luke

**Comment by f2prateek** [comment]
Sorry about this - looks like we need to do a bit more testing on our end what the criteria for rejection is - we might have incorrectly assumed that adding an opt out would fix the issue.

From what I can tell, part of the problem seems to be that the CoreBluetooth framework gets linked automatically - so yup we would either refactor it into a Subspec or use reflection like we do for advertising ID.

I've pushed a branch `no-bluetooth` https://github.com/segmentio/analytics-ios/tree/no-bluetooth that should fix the issue in the meantime.

`pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => 'no-bluetooth'`

**Comment by BenjaminPrieur** [comment]
Hi guys,

I have the same problem with the location SDK.
Can you set it as optional or something like that?

Thx,

Benjamin

**Comment by f2prateek** [comment]
I've pushed a branch `no-bluetooth-location` that doesn't collect bluetooth/location at all and won't link the frameworks automatically.

`pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => 'no-bluetooth-location'`

**Comment by jonah-williams** [comment]
I had to rely on this branch in order to construct a valid submission this week. Thanks for providing it @f2prateek, any insight into next steps here? It'd be nice to have a 3.6 (4.0?) release that makes linking bluetooth and location frameworks opt-in.

**Comment by onlyafly** [comment]
@f2prateek It looks like someone at Segment has deleted the no-bluetooth branch. How can we fix this issue now?

**Comment by onlyafly** [comment]
Actually, it looks like it has been fixed in 3.5.1.

**Comment by f2prateek** [comment]
Yup it has!

**Comment by CongBaDo** [comment]
I am using 

> pod "Analytics", "3.5.1"
And the BlueTooth permission is still there 
Any helps
