### ISSUE TITLE
'Application Opened' should record referring_application

### ISSUE THREAD

**Issue by arabold** [segmentio/analytics-ios#627]
I'm using `trackApplicationLifecycleEvents` to track "Application Opened", "Application Updated", etc. Following the documentation in the [Native Mobile Spec](https://segment.com/docs/spec/mobile/#application-opened) this _should_ also track referrer and whether is was launched from background or not. It does none of that... Instead it tracks the build number. That's also great, but this discrepancy between docs and implementation makes it difficult to work with. We're spending a great amount of time debugging to find out why things aren't working as someone would expect.

Having that said, I think improving lifecycle events ("Application Backgrounded" when backgrounded, "Application Opened" when foregrounded, etc.) would be pretty straight forward by extending the `handleAppStateNotification` method. Right now we're tracking an additional "Application Foregrounded" which tracks both new app launches and restoring from background as a workaround. I'll leave this bug entry here for further discussion.

**Comment by f2prateek** [comment]
As per the docs:

>  This event does not wait for attribution information to be received but may include information about referring applications or deep link URLs if available to the application upon open.

The spec only suggests that the event _may_ contain this information. The automatic instrumentation does not collect this information, but you can certainly trigger those events yourselves.

One thing that's not clear in the doc, events defined by the spec and events instrumented the library are different. The spec is meant to define a common set of semantic events and fields so that downstream partners can interpret them correctly. As you'll note, we don't collect every event or properties defined in the spec, and sometimes even send more information than what the spec documents if available.

But does make sense to add it by default. I've re-purposed the issue to keep track of this.

**Comment by f2prateek** [comment]
Also might be a while before we get around to this, but happy to accept a PR!

**Comment by f2prateek** [comment]
Forgot the close the issue, but we do support this now! https://github.com/segmentio/analytics-ios/blob/dev/Analytics/Classes/SEGAnalytics.m#L153
