### ISSUE TITLE
Unnecessary removal of SEGUserIdKey key on different targets than TARGET_OS_TV.

### ISSUE THREAD

**Issue by aleksandergrzyb** [segmentio/analytics-ios#671]
**Description of issue:**

In [this](https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L290) line string is added for `SEGUserIdKey` key only for `TARGET_OS_TV` target, but on [this](https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L502) line `SEGUserIdKey` key is removed for all targets.

I think it's just a simple mistake and this line should be moved under `#if TARGET_OS_TV`.

**Comment by tonyxiao** [comment]
Thanks for spotting this @aleksandergrzyb . Just to confirm, is it actually causing any issues for you in production usage?

**Comment by aleksandergrzyb** [comment]
None, just something that I noticed investigated other problem reported in #670. Thanks! 👍

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-130

**Comment by f2prateek** [comment]
hey @aleksandergrzyb, I was taking a look here, and the behaviour was actually correct. The reason for doing it this way is because originally we used to set `SEGUserIdKey` on all targets. In the new version only set `SEGUserIdKey` on tvOS, but for older customers updating, we still need to delete the unused key for them.

This isn't clear in the code though, so I'll add a comment to fix that.

**Comment by f2prateek** [comment]
That being said, since it's been a long time since this was the beahvoiur, I think it's ok to remove it now. I'll be sending a PR shortly.
