### ISSUE TITLE
Security Issue — segmentio.queue.plist is unencrypted by default.

### ISSUE THREAD

**Issue by thefaj** [segmentio/analytics-ios#693]
The default use of Segment's library on iOS leaves the queue plist file unencrypted in the user's Application Support directory. This is a security and privacy issue.

**Comment by f2prateek** [comment]
Will defer to @tonyxiao here, but my understanding is:

1. iOS encrypts the file system. As such, any data stored is encrypted by the OS by default.
2. We store the queue data within the application sandbox. iOS protects this by restricting access to this file to only the host app (i.e. other apps can't read this).
3. If you'd like, you can still use crypto interface https://github.com/segmentio/analytics-ios/blob/dev/Analytics/Classes/Crypto/SEGCrypto.h.

**Comment by thefaj** [comment]
These are all correct, except the user (who is the single most important person in the app's execution) has a clear text file on their iOS device that contains a massive and very granular breadcrumb trail of their activities within the app. The app developer doesn't realize their user's information is exposed unless they all inspect this open source library. 

There are HUGE privacy and security issues around an unencrypted file that lives on a user's device. If they get searched by CBP while re-entering the States, this exposes all of their activity to a department that vacuums up personal information for future crimes. 

Please do *the right thing* and encrypt any data that gets persisted. This should be Job #1 for any developer—protect liberty and do no harm.

**Comment by thefaj** [comment]
I expect when you do fix this problem issue, you alert all of your app developers about the situation. This is critical.

**Comment by ejcx** [comment]
Hey @thefaj thanks for filing this issue.

I work on Security Engineering here at Segment. This is something that is on our roadmap to work on. We want to make the data encrypted by default and store the key in the keychain.

This is absolutely not a "HUGE privacy and security issue" _whatsoever_. Apple has gone to great lengths to protect their devices. The filesystem is encrypted by default for example. At the end of the day, if the key is stored on the device it can be recovered by the user. Making the plist file encrypted by default adds defense in depth and is a good practice, but doesn't actually guard against the threat you listed as long as the key is also stored on the device.

Physical access to a device is always considered game over in the security world.

**Comment by thefaj** [comment]
I disagree with Segment's lax regard for user security and privacy, and I will be advising my clients against using this library until it's fixed. Please do a better job.

**Comment by thefaj** [comment]
@ejcx Why would you include a decryption key inside the app? The server would want to decrypt the data, not the sending client. https://en.m.wikipedia.org/wiki/Public-key_cryptography

**Comment by f2prateek** [comment]
@thefaj To put the severity of this issue in perspective, consider the following:

a) In typical cases, this queue is empty (we try to flush on a timer and on application exit). If the flush does fail, only events taken by a user since the *last successful upload* are still queued on the device. This is by no means the same as "a massive and very granular breadcrumb trail of their activities within the app" as you described.

b) Other analytics tools like Mixpanel and Amplitude don't do this either (though certainly not that this alone should be a reason why).

c) The attack you're describing requires the attacker to already have access to an unlocked device. This already gives the attacker access to the application itself, which typically expose more sensitive than the data queued by this library.

For c), consider the following two hypothetical apps that may use Segment:

1. An email app. By granting the attacker access to an unlocked device, the attacker can read your entire email history by simply opening the app and navigating to the inbox.

2. A taxi hailing app. By granting the attacker access to an unlocked device, the attacker can read your entire ride history by simply opening the app and navigating to the ride history page.

In both of the cases, critical sensitive data is already surfaced via UI by the host app - this is the case with most apps. However, for the small percentage of apps that do not do this and would still like to encrypt queued events, they can use the `SEGCrypto` protocol (if you need help integrating this, feel free to email friends@segment.com for support).

Re: signing messages with a public key — the library needs to be able to read the data stored on disk. e.g. customers use the [`SEGHTTPClient` API](https://github.com/segmentio/analytics-ios/blob/dev/Analytics/Classes/Internal/SEGHTTPClient.m#L36) to read the events being uploaded and accordingly modify contents of those events at the time of the upload. This requires the decryption key to be available to the app.

As an aside, for the future, we've considered moving the queueing layer to outside the Segment integration and run before all client side integrations. This would also require the library to be able to decrypt the events as the the integrations (e.g. https://github.com/segment-integrations/analytics-ios-integration-mixpanel/blob/master/Pod/Classes/SEGMixpanelIntegration.m#L123) need to be able to read the event data.

I hope this explains why the queued data isn't encrypted by default and why we think that's generally ok (and for the few apps that it isn't — they have the ability to do so with `SEGCrypto`).
