### ISSUE TITLE
Add category parameter to screen tracking

### ISSUE THREAD

**Issue by joelmarquez90** [segmentio/analytics-ios#740]
There is something weird. You actually have support for the `category` parameter on the `screen` tracking method on both [Android](https://segment.com/docs/sources/mobile/android/#screen) and [Xamarin](https://segment.com/docs/sources/mobile/xamarin/#screen), but not on [iOS](https://segment.com/docs/sources/mobile/ios/#screen).

And what's more weird is that on the [Screen spec](https://segment.com/docs/spec/screen/) you don't mention it anywhere.

Why do you have this inconsistency of parameters support / documentation?

**Comment by f2prateek** [comment]
The `category` as a top level field is being deprecated. You should send it as a property instead. 

Android did deprecate this in the JavaDocs https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L639; but not in our public docs. We'll get that updated.

We'll also get this fixed in Analytics.NET (which is replacing Analytics.Xamarin).

I'm closing this issue here as there isn't any action item for the analytics-ios library.

**Comment by f2prateek** [comment]
Sorry about the confusion, I've created internal follows up tickets to get this fixed in Analytics.NET and the docs for analytics-android updated.

**Comment by joelmarquez90** [comment]
Thanks @f2prateek !
