### ISSUE TITLE
Distinct ID 00000000-0000-0000-0000-000000000000 in Mixpanel

### ISSUE THREAD

**Issue by IsaiahJTurner** [segmentio/analytics-ios#796]
I am using Mixpanel + Analytics iOS with segment and am seeing lots of users in Mixpanel with the distinct id `00000000-0000-0000-0000-000000000000`. If you search this project for "00000000-0000-0000-0000-000000000000" you will find no results which makes me believe that IDFA tracking disabled is not being handled. Please see https://github.com/BranchMetrics/ios-branch-deep-linking/blob/b2cd3c456e96bfb4981fbcfac5d5ad7f41bba0a3/Branch-SDK/Branch-SDK/BNCSystemObserver.m#L64 for an example of how Branch handles this scenario.

**Comment by f2prateek** [comment]
We still the advertising ID as `000...`, you should rely on the field `adTrackingEnabled` to see whether the value should be used or not.

**Comment by f2prateek** [comment]
Code here https://github.com/segmentio/analytics-ios/blob/7331756df97c0417af5038bbb08ba7b4b3a0202b/Analytics/Classes/Internal/SEGSegmentIntegration.m#L169-L175

**Comment by IsaiahJTurner** [comment]
I also opened this ticket to help track a potential backend resolution to this: segment.zendesk.com/hc/requests/160806

**Comment by f2prateek** [comment]
If the current default behaviour does not work for you, here's how you can change it:

1. Disable automatic advertising ID collection.
```
SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:@"YOUR_WRITE_KEY"];
configuration.enableAdvertisingTracking = @NO;
...
[SEGAnalytics setupWithConfiguration:configuration];
```

2. Track the advertising ID yourself. You can do this either by sending this in your calls manually, or by using a middleware.

**Comment by IsaiahJTurner** [comment]
@f2prateek thanks for your response but respectfully, I'd like another engineer to take a look here. Replies like "You can do this either by sending this in your calls manually, or by using a middleware." are not helpful without code examples. Disabled IDFA collection is also not a solution as the IDFA provides valuable information. I think your teammates at Segment would agree that it's important for an analytics platform to **uniquely identify users**.

**Comment by IsaiahJTurner** [comment]
As you can see this is very common behavior. In addition to Branch metrics, Mixpanel's own library uses a different identifier when the IDFA is not available. Please see: https://github.com/mixpanel/mixpanel-swift/blob/3aea168c156eb521086587e07b501a8bccdf19c5/Mixpanel/MixpanelInstance.swift#L576

**Comment by f2prateek** [comment]
> . Disabled IDFA collection is also not a solution as the IDFA provides valuable information.

I agree - hence I suggested if the defaults don't work for you can disable the default and customize the collection to your liking :)D

>  uniquely identify users.

that's what the `userId` and `anonymousId` are for. You can read more about identities in Segment at https://segment.com/docs/spec/identify/#identities

**Comment by f2prateek** [comment]
It also sounds like you are specifically referring to Mixpanel here, as Mixpanel joins users based on the advertisingId. This is behaviour specific to the Mixpanel integration (we integrate with over hundreds of tools, some of whom expect the raw advertising value of `0000..`), hence I don't think a fix in the library would not be the right place to make this change. 

The server side integration Mixpanel should be updated send a `0000..` advertising ID as the distinct Id. Since the code for this component is closed source, the Zendesk ticket is the right avenue to escalate this issue 👍

**Comment by IsaiahJTurner** [comment]
@f2prateek OK (last message) so just to confirm this is the expected behavior:
1. Customer creates Segment account.
2. Customer installs `analytics-ios` with default settings.
3. Customer sets up Mixpanel integration.
4. Customer sets up an event "Application Opened"
5. User A (on a device with limit tracking enabled) installs and opens app.
6. User B (on a different device with limit tracking enabled) installs and opens app app.
7. User A and User B show up as the same user in the Mixpanel dashboard, contrary to how all other non-segment analytics platforms work.

**Comment by f2prateek** [comment]
It also sounds like you are specifically referring to Mixpanel here, as Mixpanel joins users based on the advertisingId. This is behaviour specific to the Mixpanel integration (we integrate with over hundreds of tools, some of whom expect the raw advertising value of 0000..), hence I don't think a fix in the library would not be the right place to make this change.

The server side integration Mixpanel should be updated send a 0000.. advertising ID as the distinct Id. Since the code for this component is closed source, the Zendesk ticket is the right avenue to escalate this issue 👍

**Comment by f2prateek** [comment]
Additionally re: https://github.com/segmentio/analytics-ios/issues/796#issuecomment-435279064 ; by default the Mixpanel setting for `Use Advertising ID for Distinct ID` is disabled. Hence you would not see User A and User B show up as the same user until you enable the setting `Use Advertising ID for Distinct ID`.

**Comment by IsaiahJTurner** [comment]
@f2prateek I checked Mixpanel's dashboard/documentation as well as Segment's and can't find a setting called "Use Advertising ID for Distinct ID" could you direct me to where this is?

**Comment by IsaiahJTurner** [comment]
@f2prateek got it, very strange indeed! Apologies for my frustrations earlier. Understand you've got a lot on your plate. Really appreciate the more recent quick and helpful replies! I'm still waiting (hoping?) for a reply on Zendesk.
