### ISSUE TITLE
Integrations don't work without Cocoapods

### ISSUE THREAD

**Issue by scalessec** [segmentio/analytics-ios#802]
Integrations are not working for us. 

We're using Segment inside of a dynamic framework, which means we're not able to use Cocoapods (for more details, you can refer to [the issue we opened over at the Segment Firebase integration project](https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/35))

I'm assuming the issue is related to the lack of CocoaPods, although it's not entirely clear to me why that would be the case.

Here's a very simple integration just for debugging purposes (note that we're not actually writing our own integration):

```swift
class TestIntegration: NSObject, SEGIntegration {
    public func screen(_ payload: SEGScreenPayload) {
        print("INTEGRATION SCREEN: \(payload.name)") // never invoked
    }
}

class TestIntegrationFactory: NSObject, SEGIntegrationFactory {
    static let shared = TestIntegrationFactory()
    
    func create(withSettings settings: [AnyHashable : Any], for analytics: SEGAnalytics) -> SEGIntegration {
        return TestIntegration() // never invoked
    }
    
    func key() -> String {
        return "TestIntegration" // invoked
    }
}
```

And then:

```swift
let config = SEGAnalyticsConfiguration(writeKey: "abc123")
config.trackApplicationLifecycleEvents = false
config.recordScreenViews = false
config.use(TestIntegrationFactory.shared)
SEGAnalytics.setup(with: config)
SEGAnalytics.debug(true)
        
SEGAnalytics.shared().screen("foo")
```

`key()` is invoked on `TestIntegrationFactory`, but that's the only method that executes. `TestIntegration` is never instantiated. All outgoing logs to Segment are missing integrations:

```swift
integrations = {
};
```

I've tried the above in a separate test project outside of our dynamic framework, and got the same result. When using the Segment Firebase Integration linked above, we're seeing the exact same behavior as this test.

**Comment by f2prateek** [comment]
Using integrations via CocoaPods is supported, but not via Carthage or manual installation at the moment. There’s nothing blocking Carthage from being supported as this library already supports it, but we have to write Cartfiles (at the least) for each of our integrations. This may change in the future if there is a large demand for it, but at the moment it is not supported. I recommend writing in to our support team with which integrations you’d like to be supported via Carthage (they’ll route it to the right team for you).

As to your issue - the library initializes integrations at runtime by making a request to the Segment API and seeing which integrations were enabled for the given project. The use method just tells the SDK - I’d like to use this integration in device mode if it’s enabled for my project.

For the test integration you shared - I see two problems with the code as is. First, abc123 is not a valid writeKey. Since there is no project associated with this writeKey and hence no enabled integrations for this project. Secondly, even if this was a valid writeKey, there is no integration named “TestIntegration” in Segment, hence the API would never say it is enabled and the library would never initialize it.

**Comment by scalessec** [comment]
The manual integration started working after we enabled Firebase in Segment. Thanks!
