### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by WarSunsOfPeace** [segmentio/analytics-ios#824]
With iOS support add for Swift Package Manager in Xcode 11 can we get that added to this project.

**Comment by rosskimes** [comment]
Any plans for this now that Xcode 11 (with SwiftPM support) is officially out?

**Comment by sourabhguptavc** [comment]
Any update on this issue?

**Comment by bdrelling** [comment]
Any updates?

**Comment by bsneed** [comment]
I left some commentary on your PR linked above.  This will likely not make it in until the 4.0 beta arrives toward March, but I'll try to make sure it's included there.

**Comment by bdrelling** [comment]
@bsneed Wondering if there's any more updates on this.

Also, I am not the author of any PRs opened in this repository. I believe you left a comment for another author that seems to have gone MIA, unfortunately.

**Comment by bsneed** [comment]
@bdrelling it is on our roadmap, yes.  While I don't have an exact date just yet for it's inclusion other than soon, it will definitely make it in along with swift language improvements.

**Comment by andreyz** [comment]
+1 on SwiftPM support. What's stopping you?

**Comment by ninjaproger** [comment]
+1

**Comment by bsneed** [comment]
To expedite this inclusion, a PR that has working test suite, and verifies that Cocoapods and Carthage continue to work will be more helpful than +1's.  I've asked these questions a number of times but no one seems to answer.  I thank you all for your interest, but in terms of priorities, this is low beyond my own personal wish that it get done.

**Comment by andreyz** [comment]
> To expedite this inclusion, a PR that has working test suite, and verifies that Cocoapods and Carthage continue to work will be more helpful than +1's. I've asked these questions a number of times but no one seems to answer. I thank you all for your interest, but in terms of priorities, this is low beyond my own personal wish that it get done.

Well, I don't get paid to support a paid SaaS SDK, but someone developing this library does. I did gave a conversion a quick stab, but this was much more involved than 1h I was willing to invest in already paid product (Segment).

**Comment by bsneed** [comment]
@andreyz thanks for your attempt.  if you can't make the changes and this is critical to you, please  contact Segment support and escalate through there.  That's part of what drives our priorities.  As I mentioned, this is on our roadmap because *we*, the libraries team here at Segment, want it.  My apologies that the timing of when we'll be able to do it, and your desire for it don't line up.

**Comment by dmiluski** [comment]
Thanks @mark-shape https://github.com/mark-shape for adding this. I was wondering if there were instructions/thought for how to also include an integration?

While integrating SegmentAnalytics alone via SPM was successful. When also attempting to include Objective-C based implementations I failed due to inability to locate the Segment framework dependency in the Objective-C Code base.

Context:
Given a move away from Cocoapods early this year to Carthage, I had attempted to pull in Firebase integration.
https://github.com/segment-integrations/analytics-ios-integration-firebase

With the attempt to move towards SwiftPM I wasn't sure how to include? Add Package to the integration repo? My first attempt to integrate copied the raw class code into my project to link and test. Unfortunately, that code wasn't able to find the Segment package. 

Wondering if I did it wrong? Or if there were other successful approaches with SwiftPM + Integrations?

**Comment by mark-shape** [comment]
@dmiluski I actually spent a bit of time on the Firebase integration for another project, I'm not 100% sure all of it works, but you can have a look at https://github.com/mark-shape/analytics-ios-integration-firebase 🙂

**Comment by dmiluski** [comment]
@mark-shape , oh that's an interesting approach. Thanks for the link, I'll toy around with it and see if I can submit some SwiftPM support PR to Firebase/Intercom Integration repos.

**Comment by bsneed** [comment]
FWIW, the latest analytics-ios has SPM support.  It hasn't spread out to destinations yet though.

**Comment by dmiluski** [comment]
@bsneed  I saw that which has me pretty excited prompting these questions. It would mean, nearly everything in my project could potentially be changed to SwiftPM with the exception of Intercom. With Analytics-iOS being pulled in via SwiftPM, I was looking to figure out how to get the integrations working to.

**Comment by bsneed** [comment]
@dmiluski you might be able to package it as a binary and store a SPM binary package in another repo.  We've looked into this a bit as there's a number of integrations that are source-only binaries.  See here: https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

Though I haven't dug in too much, I'm not sure if the source binary *has* to be an xcframework, or if it could be bundled within yet-another-framework.
