### ISSUE TITLE
registeredForRemoteNotificationsWithDeviceToken doesn't accept FirebaseCloudMessaging token

### ISSUE THREAD

**Issue by bteng22** [segmentio/analytics-ios#869]
Our team's notifications are powered through Firebase Cloud Messaging. When `didRegisterForRemoteNotificationsWithDeviceToken` callback is invoked we have a handle to the fcmToken through `Messaging.messaging().fcmToken` and we're forwarding this token through to Segment's `registeredForRemoteNotificationsWithDeviceToken` as shown below

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  if Messaging.messaging().fcmToken != nil {
    let firebaseCloudMessagingToken = Data(Messaging.messaging().fcmToken!.utf8)
    SEGAnalytics.shared()?.registeredForRemoteNotifications(withDeviceToken: firebaseCloudMessagingToken)
  }
}
```

However, whenever we read the token on Segment, the device ID is invalid. We confirmed the `fcmToken` is correct by logging it locally and successfully sending notifications to the device directly, but somewhere along the way Segment is decoding it differently than we expect. Are we missing something here or does Segment need to be able to accept device tokens from both APNS and FCM?

The code in suspect is here https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L410

**Comment by bsneed** [comment]
Hi @bteng22!  I think what should be getting passed to Segment is the value passed into the deviceToken parameter, not the fcmToken.  I don't know what the fcmToken looks like as a string off hand, but we're expecting to convert it to a hexadecimal string.  If it's not coming across correctly, I suspect this conversion is failing due to the contents of the data it's being given.

**Comment by nutlike** [comment]
Is there another possibility to attach the deviceToken to the device context? I also want to pass the FCM token to Segment (which would relay it to Customer.io which we use for sending push notifications [via Firebase Cloud Messaging]). The Segment Android SDK offers a [putDeviceToken](https://github.com/segmentio/analytics-android/blob/9ad041fbec94424f321758cb73ed2683f3f7f5e5/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java#L250) method for this which adds the information to the static device context. I am not super familiar with iOS/Objective-C and any pointers into the right direction would be appreciated.

**Comment by levibostian** [comment]
Commenting on this issue as it is still relevant today. 

FCM tokens are `String` format and you can send push notifications to the device without any need to modify the token. An example of a valid FCM token is: 
```
fLf2hGpARYKk37l3uvGYqN:APA91bHHTA89IFwqTVzsA4-ivc_PjTDsPRU3D266CrZx9-GzxI3I603lihp3ZGNGd9fulITua20CEP1NJGhP0LugCIiXL-YZYLY51_flTGeWhqUpNx9pNlC_LuODSg421qnSx9mH1p8G
```
The FCM iOS SDK will give you this `String` and you can use it directly to send pushes. 

APN tokens are `Data` format and in order to send push notifications to the device, the token needs to be [converted in a special way](https://nshipster.com/apns-device-tokens/) to `String` format. This is what the Segment iOS SDK does for you already. When you call [`registeredForRemoteNotificationsWithDeviceToken`](https://github.com/segmentio/analytics-ios/blob/6e5dc12663a96081f375f11441f8d1a4def62aec/Segment/Classes/SEGAnalytics.m#L437), the Segment SDK will call a function [`deviceTokenToString`](https://github.com/segmentio/analytics-ios/blob/master/Segment/Internal/SEGUtils.m#L153). This function does the special conversion from `Data` to `String` for you. 

Note that this conversion of APN's token `Data` to `String` is not a simple: `String(data: deviceToken, encoding: .utf8)`. As explained [here](https://nshipster.com/apns-device-tokens/) APN device tokens are unique `Data` objects and therefore need to be uniquely handled. 

After you do the special conversion for APN tokens, you should see a string similar to this valid APN token:
```
ED82B1233767D64FFBDDC2894061AEC21D751D0B73C7DE108514AEEFAAE47AFC
```

Because the Segment iOS SDK always calls `deviceTokenToString` when you call `registeredForRemoteNotificationsWithDeviceToken`, the Segment SDK is assuming that you are only using APN in your app. Therefore, I cannot find a way today to send FCM device tokens to Segment using the iOS Segment SDK.
