### ISSUE TITLE
Consider changing release numbering to include min iOS changes as major changes

### ISSUE THREAD

**Issue by cayleyh** [segmentio/analytics-ios#960]
We were recently hit by https://github.com/segmentio/analytics-ios/commit/b82f0ed082ee28e33504c9f543d1e75f7da90c5e.

We were not able to upgrade the library to a version that included the fix however, because that version also included a change in the minimum supported iOS version.

This problem was very high severity for us, and I suspect other customers. It has resulted in a number of customer complaints because Segment continues to set the wrong data every time they open their apps, and has resulted in a lot of work for us to go and manually fix integrations where the wrong data for the user has been sent because of this bug.

I would suggest 2 process changes / improvements for the team to consider:

- Issues like this need to be fixed for the supported iOS versions when they were introduced, so customers do not have to resort to dynamically patching pods themselves to get the fixed version

- The version numbering on releases should consider changes to minimum iOS version as breaking changes semantically. This would better indicate to me as a customer that there are significant difference between 4.0, 4.0.3, and 4.1 (ie. each of those does not support the same iOS versions). It also better allows you as a team to push patch releases for older library versions for bugs like this that have significant customer impacts.

I'm happy to provide more details on what we saw, how we fixed it, and how the suggestions above would help issues like this in the future.

**Comment by bsneed** [comment]
Hi @cayleyh, 

Do you mean the fix b82f0ed applied was a problem, or what it fixed was a problem before?  If you mean the latter, the issue was discovered on July 1st, and fixed on July 13th, which seems like a decent turnaround for something marked as pre-release on Github.

Re versioning, I completely understand where you're coming from there.  In the research we did internally, we found that most all customers we checked were pinned to the 3.x series given it's lifetime.  Meanwhile, we were receiving a great deal of pressure to support SPM, which as you know doesn't support those alpha/pre/etc markers within Xcode.  It wasn't our favorite path forward, but seemed like our best option with iOS 14 looming, SPM support getting added and overall breaking changes that were being introduced.  We decided to make 4.0 our beta release and worked on it for many months.  4.1 being our first stable release of the 4.x series.

I'm in no way attempting to make excuses, just passing along information as to what was happening and what constraints we were under.  We don't plan any breaking changes past 4.1, only bug fixes and feature additions.  Breaking changes wouldn't come till 5.0 which is likely down the road quite a bit.

At any rate, I definitely understand your frustrations and apologize we weren't able to come up with a better way to support all 3 package managers in a more consistent way.  We'll continue to look at this in the future and do better where we can.
