### ISSUE TITLE
Anonymize userId

### ISSUE THREAD

**Issue by miquelalvarado** [segmentio/analytics-ios#979]
(Related with #974 but NOT the same)

Hi,

In AdevintaSpain we are implementing several changes in our apps to be compliant with some privacy regulations. As a result we have implemented a middleware which anonymises some of the information sent depending on the user's privacy preferences.

One of the values we are anonymising is the `userId` when the user is sending an event. To do this we have implemented a middleware which sets the userId to nil depending on the user's privacy preferences. That worked as expected until we updated to Segment's version 4.1.0 in where you introduced this change:

```
// Do not override the userId for an 'alias' action. This value is set in [alias:] already.
 if (![action isEqualToString:@"alias"]) {
     [payload setValue:[SEGState sharedInstance].userInfo.userId forKey:@"userId"];
}
```

This is called from `SEGIntegrationsManager` which is a middleware that you introduce in the last position of the runner after we set all the middlewares when initializing `Analytics` object, making impossible for us to leave the payload as the output from our last middleware. This behavior is different than Android's in which they haven't any final private middleware so it would be nice to have the exactly same behavior in iOS.

Please note this is important for us as we need to be compliant with the privacy laws in the country and we haven't found a way to workaround this issue in the meantime.

Thanks!

**Comment by bsneed** [comment]
Hi @miquelalvarado.  This behavior was present prior to 4.1, the only thing that changed is where the data is coming from to fill it.  What's the purpose of keeping the userId locally within the Segment library and nil'ing via a middleware on the way out?  Could you just set it to nil within the segment library and get the expected behavior?  If I change how that works above, I'm not sure what the ramifications would be to other customers.  Middleware wasn't intended to change top level items in the payload even though it is possible on many of them, but that's on us for not explicitly calling it out.

There's also an experimental feature you could check out as well.  See `rawSegmentModificationBlock` on SEGAnalyticsConfiguration.h, it could take care of this for you.

**Comment by miquelalvarado** [comment]
It's kind of a strange use case but we need to anonymize tracks and keep using real `userId` in identifies. That's why we have created a middleware that only sets to nil userId for trait events.
I understand that changing the current behavior my affect to other customers but what we should accomplish is to have the same behavior in any client SDK, in this case Android's and iOS. As of today their middlewares allow this kind of conversion and they have the certainty that what they change in a source middleware won't be changed later by the sdk. In iOS version the SDK is inserting the `SEGIntegrationsManager` middleware in the last position doing some black-boxed magic. That's what I think should be reconsidered for future versions IMHO.

That being said, we will try `rawSegmentModificationBlock` but as I'm reading in the documentation will be removed eventually so I'm afraid we can lose this functionality at some point 😞.

**Comment by bsneed** [comment]
Hi @miquelalvarado, I see.  I can assure you rawSegmentModificationBlock isn't going to go away.  At most, it might move out of being experimental, but even that wouldn't be anytime soon.  If that modification block bit doesn't work for you, please reopen this issue and we'll see what other options there are.

Thanks!
