### ISSUE TITLE
Analytics 4.1.3 Error In CocoaPods Update

### ISSUE THREAD

**Issue by rwgrier** [segmentio/analytics-ios#989]
I am attempting to update from Analytics 4.1.2 to 4.1.3, and when I do a `pod update`, I get the following error in the console: 

`[!] The 'Pods-xxxxxxx' target has transitive dependencies that include statically linked binaries: (Analytics)`

My Podfile has the `use_frameworks!` flag set, I do not have `use_frameworks! :linkage => :static` in my Podfile. I even tried `use_frameworks! :linkage => :dynamic` and that did not work. I receive the same error every time I attempt to update. 

CocoaPods: `1.10.1`
Xcode: `12.4 (12D4e)`
Platform version (in the Podfile): `platform :ios, '11.0'`

Am I missing an obvious step here? Any guidance would be helpful.

**Comment by jellis-fox** [comment]
+1 this update appears to have broken our ability to update the segment pod, with no clear workaround (also similar to https://github.com/segmentio/analytics-ios/pull/968#issuecomment-789043832)

**Comment by Noobish1** [comment]
I'm seeing this also with an internal Cocoapod. (I'm the commentor that @jellis-fox mentions above).

**Comment by wvabrinskas** [comment]
+1 to this. 

I am also having this issue. Same environment. Setting `use_frameworks! :linkage => :static` is not a valid solution for us.

**Comment by cf-lam** [comment]
@sergiymomot I tried including Segment directly into my dynamic framework by copying all the objective-c files from the Segment source code into my framework target. However, I couldn't build the framework because I kept running into an error about "include of non-modular header inside framework module" when I tried to use Segment in my Swift files within the same framework. Looked at https://stackoverflow.com/a/37072619/15261204. Basically I have a dynamic framework that I include in my app target as well as other dynamic frameworks, and I want to be able to use Analytics everywhere and am running into runtime issues where it says duplicate symbols are found. Those issues are due to Analytics now being a static library that I am including in multiple dynamic frameworks, which causes the Analytics code to be copied for each of those dynamic framework targets.

**Comment by cf-lam** [comment]
I was running into a runtime issue related to using CocoaPods to include Analytics in a dynamic framework that I then included as a framework dependency for other dynamic frameworks and an app target. I was getting runtime errors about duplicate symbols found.

Dependency looked like this:

Analytics pod <-- Shared.framework

Shared.framework <-- Feature.framework

Shared.framework <-- App target
Feature.framework <-- App target

Pod file looked like this:

```
shared_pods
    pod Analytics
    .... other pods
end

target 'Shared' do
    project 'Shared/Shared.xcodeproj'
    shared_pods
end

target 'Feature' do
    project 'Feature/Feature.xcodeproj'
    shared_pods
    .... other pods
end

target 'nOCD' do
    shared_pods
    main_project_pods
    .... other pods
end
```
 
The fix was not to include pod analytics for all the other frameworks and targets, just Shared, so that it looks like


```
shared_pods
    .... other pods
end

target 'Shared' do
    project 'Shared/Shared.xcodeproj'
    shared_pods
    pod Analytics
end

target 'Feature' do
    project 'Feature/Feature.xcodeproj'
    shared_pods
    .... other pods
end

target 'nOCD' do
    shared_pods
    main_project_pods
    .... other pods
end

**Comment by bsneed** [comment]
Looking into this today, FYI.

**Comment by dhiren92** [comment]
+1 this update appears to have broken our ability to update the segment pod

**Comment by anuvednayakzc** [comment]
+1 this update appears to have broken our ability to update the segment pod

**Comment by bsneed** [comment]
Will close this because it's a duplicate.  Please follow #991 for progress.
